services:
  argocd:
    image: argoproj/argocd:latest
    container_name: argocd-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ~/.kube:/root/.kube
      - ~/.minikube:/root/.minikube
    environment:
      - ARGOCD_ADMIN_PASSWORD=admin123
      - KUBECONFIG=/root/.kube/config
    user: "0:0"
    entrypoint: ["bash", "-c"]
    command:
      - |
        chmod 755 /root/.kube && chmod 644 /root/.kube/config && \
        export MINIKUBE_HOME=/root/.minikube && \
        argocd-server --insecure --staticassets /shared/app & \
        sleep 10 && \
        argocd login localhost:8080 --username admin --password $ARGOCD_ADMIN_PASSWORD --insecure && \
        argocd cluster add kind-kind --name kind-kind --kubeconfig /root/.kube/config --upsert && \
        tail -f /dev/null
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/var/lib/loki
      - ./loki-data/wal:/wal
    user: "10001:10001"
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./opentelemetry/config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/config/dashboards.json:/etc/grafana/provisioning/dashboards/dashboards.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3000
    networks:
      - observability

  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/swag
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - URL=localhost
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=email@seudomínio.com.br
      - DHLEVEL=4096
    volumes:
      - ./letsencrypt:/config
    networks:
      - observability

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/sites-available:/etc/nginx/sites-available
      - ./nginx/conf.d/sites-enabled:/etc/nginx/sites-enabled
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - letsencrypt
      - grafana
      - prometheus
    networks:
      - observability

networks:
  observability:
    driver: bridge
